import Head from "next/head";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Portfolio from "../components/Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prodigy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        <div className="relative h-screen overflow-hidden">
          <div className="relative z-20">
            <Navbar />
          </div>
          <div className="absolute top-0 z-10 w-full h-full">
            <Hero />
          </div>
          <div className="absolute top-0 mix-blend-multiply w-full h-full bg-yellow-600 z-10" />
        </div>
        <Portfolio />
        <div className="hidden xl:block fixed bottom-36 left-0 z-30 transform -rotate-90 text-white">
          {" "}
          <p className="text-sm "> Prodigy Communications</p>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            className="transform rotate-90 h-4 w-4 fixed bottom-0 right-44"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
            />
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
            />
          </svg>
        </div>
        <div className="fixed top-0 left-28 border-r-2  h-full border-white z-30" />
      </main>

      <Footer />
    </div>
  );
}
